### PR TITLE
added CMakeLists.txt for header-only exported package

### PR DESCRIPTION
**Pull request by dand-oss**

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Can you provide some extra motivation for this ? cppy is typically used for developing python packages and as a consequence having it being pip installable and discoverable by setuptools is sufficient.

**Comment by dand-oss** [comment]
> Can you provide some extra motivation for this ? cppy is typically used for developing python packages and as a consequence having it being pip installable and discoverable by setuptools is sufficient.

Wider community - C++ builds, CI, package availability. embedding

C++ most used build tool is CMake.

https://blog.jetbrains.com/clion/2020/06/dev-eco-cpp-2020/
> The top-3 project models list remains unchanged after all these years. CMake reached the top several years ago and continues to grow:

Exporting a cmake package "manifest" allows discovery of cppy by Cmake projects.  

Cmake has to be told how to go look under python site-packages for files.  You can have cmake do anything, but extra work for each user of cppy who has a decades old cmake build system.

** C Extenstions are built with CMake, as are most C++ libraries a significant one would depend on.

As a metabuild tool, CMake supports other build systems  - ninja, make, visual studio - windows, mac, linux

Major C++ package managers work with CMake.  

Conan - Jfrog, gitlab
https://docs.conan.io/en/latest/integrations/build_system/cmake.html

Vcpg  - Microsoft
https://vcpkg.readthedocs.io/en/latest/examples/installing-and-using-packages/#cmake-toolchain-file 

Build system for C++ need not install pip packages

Github Actions for C++ Pipeline
https://www.codeproject.com/Articles/5265628/Writing-CI-Pipeline-using-GitHub-Actions-to-Build

Some people embed python rather than extend, and python is just a small add on to a mostly C++ build system.

Because Cmake is so popular, I have a python script that pulls down all the repos our system uses and builds them with cmake - say 25 or so.

**Comment by MatthieuDartiailh** [comment]
Thanks for the explanation. Please note that I have only a limited experience using C++ and do not use CMake. As a consequence I am going to trust you on this addition but would appreciate if you could answer any question that relate to CMake.

**Comment by dand-oss** [comment]
> I am going to trust you on this addition but would appreciate if you could answer any question that relate to CMake.

Yes sir, can do.

One pays a price for cmake knowledge!

Nobody "likes" the scripting language, but its the easiest way to messy things done for more serious C++ building - multi project, QT, FORTRAN, preprocessing, visual studio options, rpath...

cmake has gotten much better now with "targets" approach, called "modern cmake".

**Pull request merged**
