### PR TITLE
DOC: Fix camelCase

### PR DESCRIPTION
**Pull request by ayushman17**
- [x] Docs have been updated (for bug fixes/features)

docs update => camelCase: cppy

### Other information:
Signed-off-by: Ayushman Singh Chauhan <ascb508@gmail.com>

### CODE REVIEW

**Comment by ayushman17** [comment]
Hello??

**Comment by MatthieuDartiailh** [comment]
I always spell cppy all in lower case personally. @sccolbert an opinion on this ?

**Comment by ayushman17** [comment]
https://github.com/nucleic/cppy/pull/8/commits/7996723c2abb2268e38644d95264a8c988c626f4 ???

**Comment by MatthieuDartiailh** [comment]
It seems @sccolbert has indeed validated the CamelCase spelling. Sorry for bothering you.

**Comment by ayushman17** [comment]
No problem.
Thanks!

**Comment by sccolbert** [comment]
Eh, this is one of those things I dont care too much about. As long as its lower cased in code and code samples, I dont really care about how it’s cased in doc headers.

**Pull request merged**
